### ISSUE TITLE
meta-ls子命令增加排序参数

### ISSUE THREAD

**Issue by gaoyifan** [ustclug/ustcmirror#4]
`--sort=size` 按照仓库尺寸排序
`--sort=lastSuccess`  安装上次成功时间排序
`-r`  反序
`--pretty` 美化输出

**Comment by knight42** [comment]
现在的输出还需要怎样美化呢？

**Comment by gaoyifan** [comment]
原意是类似docker的`--pretty`参数，使用更适合人类阅读的格式（而非json）。然而已经有web页面，这可能就不需要了。

**Comment by knight42** [comment]
唔。。我觉得 json 也挺好读的。。

那我就 close 了

**Comment by gaoyifan** [comment]
@zhsj  改完后似乎http://mirrors.ustc.edu.cn/status/ 的仓库尺寸排序不太对了

**Comment by zhsj** [comment]
为啥api返回的数据不是M，G，T单位的了。。。

**Comment by zhsj** [comment]
这个issue提到的commit里并没有改api的代码呀？

**Comment by knight42** [comment]
@zhsj 在之前的 Commit 里改的，主要是因为数据库中的 size 类型从 string 改为 number 了，现在返回的是字节数
